import type { Metadata } from "next";
import "@/sass/main.scss";
import ProgressBar from "@/components/layouts/navbar/ProgressBar";
export const metadata: Metadata = {
  title: "Cornhub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProgressBar />
        {children}
      </body>
    </html>
  );
}
